AWSTemplateFormatVersion: "2010-09-09"
Description: StackSet IAM roles
Resources:

  StackSetAdministratorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "AWSCloudFormationStackSetAdministrationRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
          Action: "sts:AssumeRole"
      Policies:
        - PolicyName: StackSetAdministratorPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Action: "sts:AssumeRole"
              Resource:
                - "arn:aws:iam::*:role/AWSCloudFormationStackSetExecutionRole"

